from words import Word

es =  Word("es", 2, 1, Word.HORIZONTAL)
ischzit =  Word("isch", 5, 1, Word.HORIZONTAL)
füf =  Word("füf", 10, 1, Word.HORIZONTAL)
zäh =  Word("zäh", 7, 2, Word.HORIZONTAL)
viertu =  Word("viertu", 1, 2, Word.HORIZONTAL)
zwänzg =  Word("zwänzg", 2, 3, Word.HORIZONTAL)
ab =  Word("ab", 2, 4, Word.HORIZONTAL)
vor =  Word("vor", 9, 4, Word.HORIZONTAL)
haubi =  Word("haubi", 4, 5, Word.HORIZONTAL)
eis =  Word("eis", 1, 6, Word.HORIZONTAL)
zwöi =  Word("zwöi", 4, 9, Word.HORIZONTAL)
drüü =  Word("drüü", 9, 10, Word.HORIZONTAL)
vieri =  Word("vieri", 6, 8, Word.HORIZONTAL)
füfi =  Word("füfi", 1, 12, Word.HORIZONTAL)
sächsi =  Word("sächsi", 3, 6, Word.HORIZONTAL)
sibni =  Word("sibni", 7, 6, Word.HORIZONTAL)
achti =  Word("achti", 1, 8, Word.HORIZONTAL)
nüni =  Word("nüni", 6, 12, Word.HORIZONTAL)
zäni =  Word("zäni", 1, 10, Word.HORIZONTAL)
eufi =  Word("eufi", 9, 11, Word.HORIZONTAL)
zwöufi =  Word("zwöufi", 7, 7, Word.HORIZONTAL)

schöne =  Word("schöne", 3, 6, Word.VERTICAL)
tag =  Word("tag", 5, 10, Word.VERTICAL)
häppi =  Word("häppi", 8, 1, Word.VERTICAL)
börsdei =  Word("börsdei", 9, 6, Word.VERTICAL)
ig =  Word("ig", 2, 6, Word.VERTICAL)
ha =  Word("ha", 5, 4, Word.VERTICAL)
di =  Word("di", 5, 7, Word.VERTICAL)
gärn =  Word("gärn", 8, 9, Word.VERTICAL)
du =  Word("du", 6, 4, Word.VERTICAL)
bisch =  Word("bisch", 3, 4, Word.VERTICAL)
super =  Word("super", 12, 2, Word.VERTICAL)
hüt =  Word("hüt", 1, 3, Word.VERTICAL)
isch =  Word("isch", 3, 5, Word.VERTICAL)
tag =  Word("tag", 5, 10, Word.VERTICAL)


